version: "3"
services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    env_file: .env
    environment:
      - ENV=development
    restart: always
    volumes:
      - "./auth:/usr/src/auth"
    ports:
      - 8080:8080
  nest:
    build:
      context: ./nest
      dockerfile: Dockerfile
    container_name: nest
    restart: always
    env_file: .env
    environment:
      - ENV=development
    ports:
      - 8000:8000
    volumes:
      - "./nest:/usr/src/nest"
      - "/usr/src/nest/node_modules"
      - "/usr/src/nest/dist"
  nest2:
    build:
      context: ./nest2
      dockerfile: Dockerfile
    container_name: nest2
    restart: always
    env_file: .env
    environment:
      - ENV=development
    ports:
      - 8002:8002
    volumes:
      - "./nest2:/usr/src/nest2"
      - "/usr/src/nest2/node_modules"
      - "/usr/src/nest2/dist"
  hellofin:
    build:
      context: ./hellofin
      dockerfile: Dockerfile
    container_name: hellofin
    restart: always
    env_file: .env
    environment:
      - ENV=development
    ports:
      - 8003:8003
    volumes:
      - "./hellofin:/usr/src/hellofin"
      - "/usr/src/hellofin/node_modules"
      - "/usr/src/hellofin/dist"
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: admin
    restart: always
    env_file: .env
    environment:
      - ENV=development
    expose:
      - 5555
    ports:
      - 5555:5555
    volumes:
      - "./admin:/usr/src/admin"
      - "/usr/src/admin/node_modules"
      - "/usr/src/admin/dist"
  # scheduler:
  #   build:
  #     context: ./scheduler
  #     dockerfile: Dockerfile
  #   container_name: scheduler
  #   restart: always
  #   env_file: .env
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - "./scheduler:/usr/src/scheduler"
  #     - "/usr/src/scheduler/node_modules"
  #     - "/usr/src/scheduler/dist"
  #   environment:
  #     - TZ=Asia/Seoul