FROM openjdk:11-jre-slim-stretch as builder
WORKDIR /app
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract 

FROM openjdk:11-jre-slim-stretch 
WORKDIR /app
EXPOSE 8080
COPY --from=builder /app/dependencies/ ./
COPY --from=builder /app/spring-boot-loader/ ./
COPY --from=builder /app/snapshot-dependencies/ ./
COPY --from=builder /app/application/ ./

ENTRYPOINT ["java", "-Dspring.profiles.active=production" , "org.springframework.boot.loader.JarLauncher"]