spring:
  config:
    use-legacy-processing: true
  profiles:
    active: development
  datasource:
    url: jdbc:mysql://localhost:3306/DATABASE?characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties.useUnicode: true
      data-source-properties.characterEncoding: UTF-8
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: .
      trigger-file: reload-trigger.txt
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  swagger:
    enabled: true
    version: 2.0
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    converters:
      preferred-json-mapper: gson
#for health checker
management:
  endpoints:
    web:
      base-path: /health
      path-mapping:
        health : check